services:
    codeserver:
        container_name: codeserver
        build: .
        network_mode: host
        ports:
            - "8080:8080"
            - "8443:8443"
        environment:
            - AUTHENTICATION_MODE=password
            - HTTPS=false
            - PORT=8080
            - DEBUG=*
        volumes:
            - ./certs:/certs